In [1]:
import dotenv
dotenv.load_dotenv()

True

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./data/churn.csv", index_col=0, parse_dates=["joining_date"])

In [4]:
df.columns

Index(['age', 'gender', 'security_no', 'region_category',
       'membership_category', 'joining_date', 'joined_through_referral',
       'referral_id', 'preferred_offer_types', 'medium_of_operation',
       'internet_option', 'last_visit_time', 'days_since_last_login',
       'avg_time_spent', 'avg_transaction_value', 'avg_frequency_login_days',
       'points_in_wallet', 'used_special_discount',
       'offer_application_preference', 'past_complaint', 'complaint_status',
       'feedback', 'churn_risk_score'],
      dtype='str')

In [5]:
df.head()

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,xxxxxxxx,Gift Vouchers/Coupons,?,...,300.63,53005.25,17.0,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,0
1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,?,CID21329,Gift Vouchers/Coupons,Desktop,...,306.34,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,0
2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,Desktop,...,516.16,21027.00,22.0,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,1
3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,Desktop,...,53.27,25239.56,6.0,567.66,No,Yes,Yes,Unsolved,Poor Website,1
4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,xxxxxxxx,Credit/Debit Card Offers,Smartphone,...,113.13,24483.66,16.0,663.06,No,Yes,Yes,Solved,Poor Website,1

In [6]:
df.tail()

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
36987,46,F,6F51HFO,NaN,Basic Membership,2017-09-21,No,xxxxxxxx,Credit/Debit Card Offers,Desktop,...,-650.682759,27277.68,6.0,639.510000,No,Yes,Yes,No Information Available,No reason specified,1
36988,29,F,21KSM8Y,Town,Basic Membership,2016-06-27,No,xxxxxxxx,Without Offers,Smartphone,...,-638.123421,11069.71,28.0,527.990000,Yes,No,No,Not Applicable,Poor Customer Service,1
36989,23,F,XK1IM9H,NaN,Basic Membership,2016-09-11,Yes,CID3838,Gift Vouchers/Coupons,Desktop,...,154.940000,38127.56,Error,680.470000,No,Yes,Yes,Unsolved,Poor Website,1
36990,53,M,K6VTP1Z,Village,Platinum Membership,2017-06-15,No,xxxxxxxx,Gift Vouchers/Coupons,Smartphone,...,482.610000,2378.86,20.0,197.264414,Yes,Yes,No,Not Applicable,No reason specified,0
36991,35,M,LBX0GLR,Town,Silver Membership,2015-10-23,No,xxxxxxxx,Gift Vouchers/Coupons,Desktop,...,79.180000,2189.68,Error,719.970000,Yes,No,No,Not Applicable,Quality Customer Care,0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           36992 non-null  int64
 1   gender                        36992 non-null  str
 2   security_no                   36992 non-null  str
 3   region_category               31564 non-null  str
 4   membership_category           36992 non-null  str
 5   joining_date                  36992 non-null  datetime64[us]
 6   joined_through_referral       36992 non-null  str
 7   referral_id                   36992 non-null  str
 8   preferred_offer_types         36704 non-null  str
 9   medium_of_operation           36992 non-null  str
 10  internet_option               36992 non-null  str
 11  last_visit_time               36992 non-null  str
 12  days_since_last_login         36992 non-null  int64
 13  avg_time_spent                36992 non-null  float64
 14  avg_transaction_value         36992 non-null  float64
 15  avg_frequency_login_days      36992 non-null  str
 16  points_in_wallet              33549 non-null  float64
 17  used_special_discount         36992 non-null  str
 18  offer_application_preference  36992 non-null  str
 19  past_complaint                36992 non-null  str
 20  complaint_status              36992 non-null  str
 21  feedback                      36992 non-null  str
 22  churn_risk_score              36992 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(3), str(16)
memory usage: 6.5 MB

In [8]:
df.shape

(36992, 23)

## Columns with unclear or no-value add to modelling

In [9]:
unclear_value_add_columns = ["security_no", "referral_id"]
df[unclear_value_add_columns].sample(10)

      security_no referral_id
33092     0CGN3QE    xxxxxxxx
12607     LJUFT23    CID52001
35026     LCKVG0D    xxxxxxxx
30719     0FNOSPR    xxxxxxxx
36945     2J86HFW    xxxxxxxx
27919     CKFORJ7    CID51772
13194     WYS88VX    xxxxxxxx
21967     T9SM1SH    CID56972
23447     L68E10X    xxxxxxxx
32211     SWFIEQ0    xxxxxxxx

In [10]:
## No overlap between the columns so they don't seem to be related at all
set(df[unclear_value_add_columns[0]].unique()).intersection(set(df[unclear_value_add_columns[1]].unique()))

set()

## Date/Time based columns

In [11]:
date_based_columns = ["joining_date", "last_visit_time"]

In [12]:
df_new = df['joining_date'].apply(lambda x: pd.Series([x.year, x.month, x.quarter]))

# Rename the columns for clarity
df_new.columns = ['year', 'month', 'quarter']

In [13]:
df_new['year'].unique()

array([2017, 2016, 2015])

In [15]:
import matplotlib.pyplot as plt

In [ ]:
df_new['year'].plot.bar()

# 1. Count occurrences and sort by the year (index)
year_counts = df_new['year'].value_counts().sort_index()

# 2. Create the bar chart
# Converting index to string ensures each year gets a dedicated label
plt.bar(year_counts.index.astype(str), year_counts.values, color='skyblue')

# 3. Add labels and title
plt.xlabel('Year')
plt.ylabel('Count')
plt.title('Distribution of Years')

# 4. Optional: rotate labels if you have many years
plt.xticks(rotation=45)

plt.show()

## Columns with mixed datatypes

In [48]:
mixed_numerical = ["avg_frequency_login_days"]
df[mixed_numerical].sample(10)

      avg_frequency_login_days
3008                      25.0
23607                     25.0
29312                      5.0
25235        51.05760303514481
22290                     16.0
466                       18.0
14389                     14.0
17934                     11.0
7970                       6.0
15903                     19.0

## Numerical Columns

Columns that have a numerical

In [21]:
numerical_columns = ["days_since_last_login", "avg_time_spent", "avg_transaction_value", "points_in_wallet", "age", "churn_risk_score"]

In [22]:
df[numerical_columns].describe()

,days_since_last_login,avg_time_spent,avg_transaction_value,points_in_wallet,age,churn_risk_score
count,36992.000000,36992.000000,36992.000000,33549.000000,36992.000000,36992.000000
mean,-41.915576,243.472334,29271.194003,686.882199,37.118161,0.540982
std,228.819900,398.289149,19444.806226,194.063624,15.867412,0.498324
min,-999.000000,-2814.109110,800.460000,-760.661236,10.000000,0.000000
25%,8.000000,60.102500,14177.540000,616.150000,23.000000,0.000000
50%,12.000000,161.765000,27554.485000,697.620000,37.000000,1.000000
75%,16.000000,356.515000,40855.110000,763.950000,51.000000,1.000000
max,26.000000,3235.578521,99914.050000,2069.069761,64.000000,1.000000

## All other columns

In [51]:
other_columns = set(df.columns) - set(numerical_columns) - set(unclear_value_add_columns) - set(mixed_numerical)
other_columns

{'complaint_status',
 'feedback',
 'gender',
 'internet_option',
 'joined_through_referral',
 'joining_date',
 'last_visit_time',
 'medium_of_operation',
 'membership_category',
 'offer_application_preference',
 'past_complaint',
 'preferred_offer_types',
 'region_category',
 'used_special_discount'}

### Complaint Columns

In [ ]:
complaint_columns = ["complaint_status", "past_complaint"]

In [14]:
df.value_counts("feedback")

feedback
Poor Product Quality        6350
No reason specified         6290
Too many ads                6279
Poor Website                6271
Poor Customer Service       6252
Reasonable Price            1417
User Friendly Website       1391
Products always in Stock    1382
Quality Customer Care       1360
Name: count, dtype: int64